CREATE TABLE [dbo].[OutPut]
(
	IdOutPut INT NOT NULL IDENTITY (1,1),
	Destination NVARCHAR(100) NOT NULL,
	Balance DECIMAL NOT NULL,
	DateOut DATETIME2 NOT NULL,
	Note NVARCHAR(100) NULL,
	IdBill INT NULL,
	IdAccount INT NOT NULL,
	CONSTRAINT PK_OutPut PRIMARY KEY (IdOutPut),
	CONSTRAINT FK_OutPut_Bill FOREIGN KEY (IdBill) REFERENCES Bill(IdBill),
	CONSTRAINT FK_OutPut_Account FOREIGN KEY (IdAccount) REFERENCES Account(IdAccount)
)
