CREATE TABLE [dbo].[User]
(
	IdUser INT NOT NULL IDENTITY (1,1),
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Tel NVARCHAR(100) NOT NULL,
	IsChild BIT NOT NULL DEFAULT 1,
	IsActive BIT NOT NULL DEFAULT 1,
	UPassword BIT NOT NULL,
	Salt NVARCHAR(100) NOT NULL,
	IdSensibleData INT NOT NULL,
	IdRole INT NOT NULL,
	CONSTRAINT PK_User PRIMARY KEY (IdUser),
	CONSTRAINT FK_User_SensibleData FOREIGN KEY (IdSensibleData) REFERENCES SensibleData(IdSensible),
	CONSTRAINT FK_User_Role FOREIGN KEY (IdRole) REFERENCES [Role](IdRole)
)
