CREATE TABLE [dbo].[User]
(
	IdUser INT NOT NULL IDENTITY (1,1),
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Tel NVARCHAR(100) NOT NULL,
	BirthDate Date NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	UPassword NVARCHAR(100) NOT NULL,
	Salt NVARCHAR(100) NOT NULL,
	IdSensibleData INT NOT NULL,
	IdRole INT NULL,
	CONSTRAINT PK_User PRIMARY KEY (IdUser),
	CONSTRAINT FK_User_SensibleData FOREIGN KEY (IdSensibleData) REFERENCES SensibleData(IdSensible),
	CONSTRAINT FK_User_Role FOREIGN KEY (IdRole) REFERENCES [Role](IdRole)
)
